### ISSUE TITLE
Looping mode introduces pause equal to loop duration between repetitions

### ISSUE THREAD

**Issue by seththorn** [ceammc/SwiftRNBO#23]
When using loop mode with groove~, there is a pause equal to loop duration between repetitions.

To reproduce the behavior, set groove~ to loop in the RNBO patch

![image](https://github.com/ceammc/SwiftRNBO/assets/50844254/5828298a-bd47-4a62-985b-207ce0bd504f)

Then move the play slider to initiate playback. Wait for a second or two, and you'll hear the looping gap.

**Comment by eldarsadykov** [comment]
Thanks for pointing out!
It looks like upon loading a sample it reads additional buffer size of silence, nothing wrong with the playback, fortunately. We'll look into it.

**Comment by seth-thorn** [comment]
Thanks! Would be great to have this feature working.

**Comment by eldarsadykov** [comment]
> Thanks! Would be great to have this feature working.

Fixed! Please, download the main branch.

**Comment by eldarsadykov** [comment]
> Thanks! Would be great to have this feature working.

Fixed! Please, download the main branch. 
Thanks once again to @njazz for the solution!
